#!/bin/bash

export GEOMERATIVE_VER=12

#### Build documentation
linuxGenerateDoc

#### Build library
linuxCompile

####  Bundle for distribution
rm -fr ./distribution &&
mkdir ./distribution &&
mkdir ./distribution/geomerative/ &&
mkdir -p ./distribution/geomerative/library &&

##  Copy libs
cp ./library/geomerative.jar ./distribution/geomerative/library &&
cp ./external/batikfont.jar ./distribution/geomerative/library &&

##  Copy docs
cp ./README ./distribution/geomerative/ &&
cp ./COPYING ./distribution/geomerative/ &&
cp -r ./documentation/ ./distribution/geomerative/ &&

##  Copy examples
cp -r ./examples/ ./distribution/geomerative/ &&

##  Copy tutorial
cp -r ./tutorial/ ./distribution/geomerative/ &&

##  Copy sources
cp -r ./src ./distribution/geomerative/


##  Zip up
cd distribution
rm -f geomerative-$GEOMERATIVE_VER.zip
zip -r ./geomerative-$GEOMERATIVE_VER.zip ./geomerative/library ./geomerative/documentation/ ./geomerative/COPYING ./geomerative/README ./geomerative/examples/ ./geomerative/src/ ./geomerative/tutorial/
cd ..

