#!/bin/bash
mkdir -p library
javac -nowarn -source 1.3 -target 1.1 -classpath ./external/batikfont.jar:$PROCESSING_PATH/lib/core.jar:$PROCESSING_PATH/libraries/xml/library/xml.jar -d ./library ./src/geomerative/*.java &&
cd library &&
jar -cf geomerative.jar geomerative &&
cd ..
